#lang sicp
(define (filtered-accumulate combiner null-value filter term a next b)
  (if (> a b)
      null-value
      (if (filter a)
          (combiner (term a)
                    (filtered-accumulate combiner null-value filter
                                         term (next a) next b))
          (filtered-accumulate combiner null-value filter
                                         term (next a) next b))))
(define (sum a b)
  (define (inc i)
    (+ i 1))
  (define (prime? i)
    (define (next x)
      (if (= x 2) 3 (+ x 2)))
    (define (divider i n)
      (cond ((> (square n) i) true)
            ((= (remainder i n) 0) false)
            (else (divider i (next n)))))
    (divider i 2))
  (filtered-accumulate + 0 prime? identity a inc b))
(define (square i)
  (* i i))
(define (filtered-accumulate-iter combiner null-value filter term a next b)
  (define (iter a result)
    (if (> a b)
        result
        (if (filter a)
            (iter (next a) (combiner result (term a)))
            (iter (next a) result))))
  (iter a null-value))
(define (gcd a b)
  (cond ((= b 0) a)
        (else (gcd b (remainder a b)))))
(define (inc i)
  (+ i 1))
(define (product-of-primes n)
  (define (filter i)
    (= (gcd i n) 1))
  (filtered-accumulate-iter * 1 filter identity 1 inc n))
(define (sum-of-prime-square a b)
  (define (prime? i)
    (define (next x)
      (if (= x 2) 3 (+ x 2)))
    (define (divider i n)
      (cond ((> (square n) i) true)
            ((= (remainder i n) 0) false)
            (else (divider i (next n)))))
    (divider i 2))
  (filtered-accumulate-iter + 0 prime? square a inc b))