#lang sicp
(define (make-account balance password)
  (define counter 0)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient fund"))
  (define (deposit amount)
    (begin (set! balance (+ balance amount))
           balance))
  (define (reset)
    (set! counter 0))
  (define (count)
    (set! counter (+ 1 counter)))
  (define (call-the-cops)
    "wwwwwwwwwwwwwwwwwwwwwwwww")
  (define (dispatch p m)
    (cond ((not (eq? p password)) (lambda (x) (count)
                                    (if (= counter 7)
                                        (call-the-cops)
                                    "Incorrect password")))
          ((eq? m 'withdraw) (reset) withdraw)
          ((eq? m 'deposit) (reset) deposit)
          (else (error "Unknown request : MAKE-ACCOUNT" m))))
  dispatch)
(define acc (make-account 100 'elpsycongroo))
((acc 'secret-password 'withdraw) 40)